# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from unitree_legged_msgs/CheaterState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CheaterState(genpy.Message):
  _md5sum = "f8cc1254d33feda52dbc17fc7e4c7459"
  _type = "unitree_legged_msgs/CheaterState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[4] orientation
float32[3] position
float32[3] vBody
float32[3] vWorld
float32[3] omegaBody
float32[3] acceleration
"""
  __slots__ = ['orientation','position','vBody','vWorld','omegaBody','acceleration']
  _slot_types = ['float32[4]','float32[3]','float32[3]','float32[3]','float32[3]','float32[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       orientation,position,vBody,vWorld,omegaBody,acceleration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CheaterState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.orientation is None:
        self.orientation = [0.] * 4
      if self.position is None:
        self.position = [0.] * 3
      if self.vBody is None:
        self.vBody = [0.] * 3
      if self.vWorld is None:
        self.vWorld = [0.] * 3
      if self.omegaBody is None:
        self.omegaBody = [0.] * 3
      if self.acceleration is None:
        self.acceleration = [0.] * 3
    else:
      self.orientation = [0.] * 4
      self.position = [0.] * 3
      self.vBody = [0.] * 3
      self.vWorld = [0.] * 3
      self.omegaBody = [0.] * 3
      self.acceleration = [0.] * 3

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_4f().pack(*self.orientation))
      buff.write(_get_struct_3f().pack(*self.position))
      buff.write(_get_struct_3f().pack(*self.vBody))
      buff.write(_get_struct_3f().pack(*self.vWorld))
      buff.write(_get_struct_3f().pack(*self.omegaBody))
      buff.write(_get_struct_3f().pack(*self.acceleration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 16
      self.orientation = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 12
      self.position = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.vBody = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.vWorld = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.omegaBody = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.acceleration = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.orientation.tostring())
      buff.write(self.position.tostring())
      buff.write(self.vBody.tostring())
      buff.write(self.vWorld.tostring())
      buff.write(self.omegaBody.tostring())
      buff.write(self.acceleration.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 16
      self.orientation = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      start = end
      end += 12
      self.position = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.vBody = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.vWorld = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.omegaBody = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.acceleration = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
